#!/bin/bash
# assemble classes

die() { echo "$@" 1>&2; exit 1; }

usage()
{
    cat <<-'EOF'
	usage: xdo asm [file.j ...]

	Without arguments, assemble all classes in currently extracted jar.
	(classes which are up-to-date are not assembled again)

	If .j files are specified, just assemble these.
	EOF
    exit 1
}

[ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] && usage

# Standalone mode
if [ "$1" != "" ]; then
    for f in "$@"; do
	java_asm "$f"
    done
    exit 0
fi


[ -d "jar" ] || die "no jar/ directory. Open jar first "

asm_all()
{
    cat > Makefile.xdo <<'EOF'
SRCJ     = $(shell find . -name "*.j" )
CLASSES  = $(SRCJ:.j=.class)

all: $(CLASSES)

%.class: %.j
	@echo asm '$<'
	@java_asm '$<'
EOF
    jobs=1
    if [ -f /proc/cpuinfo ]; then
	jobs=`cat /proc/cpuinfo | grep processor | wc -l`
    fi
    make -f Makefile.xdo -j$jobs all
    rm Makefile.xdo    
}

set -e
cd jar
n=`find . -name "*.j" | wc -l`
[ "$n" = 0 ] && die "No input files. dasm first ?"
asm_all

