#!/bin/bash
# deobfuscate jar

usage()
{
    cat <<-'EOF'
	deobfuscate jar

	usage: xdo deobf [options] input.jar output.jar
        
	shorthand for:
	  xdo jar -x input.jar
	  xdo dasm
	  xdo constfix
	  xdo renmethods
	  xdo deoverload
	  xdo renfields
	  xdo restoredbginfo
	  xdo jar -c output.jar
	  xdo done

	options:
	  --nodefpkg    move classes out of default package first
	  --collapse    move all classes into package 'pkg' first, and ensure
	                unique names
	  --strip       no .j files in output.jar
	  -cp classpath paths to system/external .jars project depends on
	                (java jre's rt.jar added automatically)
	EOF
    exit 1
}

[ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] && usage

nodefpkg=""
collapse=""
strip=""
classpath=""
while [ "${1%%-*}" = "" ]; do
    if   [ "$1" = "--nodefpkg" ]; then
	nodefpkg="1"; shift
    elif [ "$1" = "--collapse" ]; then
	collapse="1"; shift
    elif [ "$1" = "--strip" ]; then
	strip="1"; shift
    elif [ "$1" = "-cp" ]; then
	shift;  [ -z "$1" ] && usage;  classpath="-cp $1";  shift
    else
	usage
    fi
done


[ "$1" = "" ] || ! [ -f "$1" ] || [ "${1%.jar}" = "$1" ] && usage
in="$1";  shift
[ "$1" = "" ] ||                  [ "${1%.jar}" = "$1" ] && usage
out="$1"; shift


###################################################################
set -e

"$cmddir"/jar -x "$in"
"$cmddir"/dasm

if [ -n "$collapse" ]; then
    "$cmddir"/move  $classpath  '*'  'pkg/$1'
    "$cmddir"/move  $classpath  --auto-rename  '**/*'  'pkg/$2'
elif [ -n "$nodefpkg" ]; then
    "$cmddir"/nodefpkg $classpath
fi

"$cmddir"/constfix   $classpath
"$cmddir"/renmethods $classpath
"$cmddir"/deoverload $classpath
"$cmddir"/renfields  $classpath
"$cmddir"/restoredbginfo

if [ -n "$strip" ]; then
    "$cmddir"/strip
fi

"$cmddir"/jar -c "$out"
"$cmddir"/done
