#!/bin/bash
# open / create jar files

die() { echo "$@" 1>&2; exit 1; }

usage()
{
    cat <<-'EOF'
	usage: xdo jar -x input.jar
	       xdo jar -c output.jar
	
	extract or create jar files
	EOF
    exit 1
}

[ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] && usage

extract()
{
    [ "$1" = "" ] || ! [ -f "$1" ] || [ "${1%.jar}" = "$1" ] && usage
    
    [ -d "jar" ] && die "jar/ directory exists. Close jar first."
    mkdir jar || die "Couldn't create jar directory."
    
    echo "Extracting $1 ..."
    unzip -q -d jar "$1"
    if [ $? -ge 2 ]; then 
	exit 2
    fi
    exit 0
}


pack()
{
    [ "$1" = "" ] || [ "${1%.jar}" = "$1" ] && usage
    [ -d "jar" ] || die "no jar/ directory. Open jar first."
    
    # Ensure .class files are up to date before packing
    "$cmddir/asm"

    echo "Packing $1 ..."
    if [ -f "jar/META-INF/MANIFEST.MF" ]; then
	jar -cfm "$1" "jar/META-INF/MANIFEST.MF" -C jar .    
    else
	jar -cf "$1" -C jar .    
fi
}


cmd="$1"; shift
[ "$cmd" = "-x" ] && extract "$@"
[ "$cmd" = "-c" ] && pack "$@"




